runtime: python313

entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
    APPENGINE_URL: https://apartments.comparison.tools
    # OAuth key as plain text environment variable
    # OAuth secret retrieved from Google Secret Manager at runtime