runtime: python312

entrypoint: gunicorn config.wsgi --bind=0.0.0.0:$PORT

automatic_scaling:
  max_instances: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
    APPENGINE_URL: https://analyze-apartments.wl.r.appspot.com