# Generated by Django 5.2 on 2025-04-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='FavoritePlace',
        ),
    ]
