# Generated by Django 5.2 on 2025-11-29 17:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_add_favorite_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
