# Generated by Django 5.2.8 on 2025-11-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_userpreferences_bathrooms_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentdistance',
            name='transit_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transit fare in USD', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='time_type',
            field=models.CharField(choices=[('departure', 'Departure Time'), ('arrival', 'Arrival Time')], default='departure', max_length=20),
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='travel_mode',
            field=models.CharField(choices=[('driving', 'Driving'), ('transit', 'Transit')], default='driving', max_length=20),
        ),
    ]
