# Generated by Django 5.2.8 on 2025-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_apartmentdistance_transit_fare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteplace',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='favoriteplace',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=5, help_text='Day of week (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='time_of_day',
            field=models.TimeField(default='12:00', help_text='Time of day for arrival/departure'),
        ),
    ]
