# Generated by Django 5.2.8 on 2025-11-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_remove_favoriteplace_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='discount_calculation',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='weekly', max_length=20),
        ),
    ]
