# Generated by Django 5.2.8 on 2025-11-30 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_change_discount_calculation_default_to_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='discount_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
