# Generated by Django 5.2.8 on 2025-11-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_add_discount_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='factor_order',
            field=models.CharField(blank=True, default='price,sqft,distance,netRent,bedrooms,bathrooms,discount', max_length=200),
        ),
    ]
