# Generated by Django 5.2.8 on 2025-12-02 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_add_factor_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_apartment_name_per_user'),
        ),
    ]
