# Generated by Django 5.2.8 on 2025-12-02 05:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_add_unique_apartment_name_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='parking_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='utilities',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='view_quality',
            field=models.IntegerField(default=0, help_text='Rating for windows/sunlight/view (0=not rated, 1-5 scale)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='balcony_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='parking_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='utilities_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='view_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='factor_order',
            field=models.CharField(blank=True, default='price,sqft,distance,netRent,bedrooms,bathrooms,discount,parking,utilities,view,balcony', max_length=300),
        ),
    ]
