# Generated by Django 5.2.8 on 2025-12-02 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_add_parking_utilities_view_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='total_cost_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='factor_order',
            field=models.CharField(blank=True, default='price,sqft,distance,netRent,totalCost,bedrooms,bathrooms,discount,parking,utilities,view,balcony', max_length=300),
        ),
    ]
