# Generated by Django 5.2.8 on 2025-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_userpreferences_total_cost_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='price_per_sqft_basis',
            field=models.CharField(choices=[('base', 'Monthly Rent'), ('net_effective', 'Net Effective'), ('total_cost', 'Total Cost')], default='net_effective', max_length=20),
        ),
    ]
