# Generated by Django 5.2.8 on 2025-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_add_price_per_sqft_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='pricing_sort_basis',
            field=models.CharField(choices=[('base', 'Base Rent'), ('net_effective', 'Net Effective'), ('total_cost', 'Total Cost')], default='base', max_length=20),
        ),
    ]
