# Generated by Django 5.2.8 on 2025-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_add_pricing_sort_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_tier_limit',
            field=models.IntegerField(default=20),
        ),
    ]
