# Generated by Django 5.2.8 on 2025-12-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0019_add_pro_tier_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(blank=True, choices=[('', 'None'), ('month', 'Monthly'), ('year', 'Annual'), ('lifetime', 'Lifetime')], max_length=20),
        ),
    ]
