"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse
import environ

# Initialize environ
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_file = os.path.join(BASE_DIR, ".env")

if os.path.isfile(env_file):
    # Use a local secret file, if provided

    env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-e&f)15o0*-pg2ul$(w&on#i5kz+a-(kk=hvyff3wg%k&!pqsor"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False if running in Google App Engine
DEBUG = "GAE_ENV" not in os.environ

# ALLOWED_HOSTS configuration
# In production, uses APPENGINE_URL from environment variable (set in app.yaml)
# Supports custom domain: apartments.comparison.tools
if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]
else:
    APPENGINE_URL = os.environ.get("APPENGINE_URL", "")
    if APPENGINE_URL:
        # Ensure a scheme is present in the URL before it's processed.
        if not urlparse(APPENGINE_URL).scheme:
            APPENGINE_URL = f"https://{APPENGINE_URL}"

        domain = urlparse(APPENGINE_URL).netloc
        # Allow both custom domain and App Engine default domain
        ALLOWED_HOSTS = [
            domain,
            "comparison.tools",
            "apartments.comparison.tools",
            "comparison-tools-479102.uc.r.appspot.com",  # Fallback to App Engine URL
        ]
        CSRF_TRUSTED_ORIGINS = [
            APPENGINE_URL,
            "https://comparison.tools",
            "https://apartments.comparison.tools",
        ]
        SECURE_SSL_REDIRECT = True
    else:
        ALLOWED_HOSTS = [
            "comparison.tools",
            "apartments.comparison.tools",
            "comparison-tools-479102.uc.r.appspot.com",
        ]
        CSRF_TRUSTED_ORIGINS = [
            "https://comparison.tools",
            "https://apartments.comparison.tools",
        ]
        SECURE_SSL_REDIRECT = True

# Application definition

# Conditional apps based on environment
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "social_django",
    "apartments",
]

# Only add development apps in DEBUG mode
if DEBUG:
    INSTALLED_APPS.extend(
        [
            "tailwind",
            "theme",
            "django_browser_reload",
        ]
    )
    TAILWIND_APP_NAME = "theme"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Only add browser reload middleware in DEBUG mode
if DEBUG:
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite is used only for Django admin and auth (not sessions in production)
# Application data (apartments, user preferences) is stored in Firestore
if not DEBUG:
    # On App Engine, we'll create a minimal database setup in /tmp
    # Since /tmp is writable but not persistent on App Engine
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "/tmp/db.sqlite3",
            "OPTIONS": {
                "timeout": 30,
            },
        }
    }
else:
    # In development, use regular file-based SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Firestore Configuration
# Firestore is used for all application data (apartments, user preferences)
# Django's built-in features (admin, auth, sessions) continue to use SQLite
FIRESTORE_PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT", "comparison-tools-479102")

# In production (App Engine), Firestore uses default service account
# In development, use Application Default Credentials or service account key
if not DEBUG:
    # Production: Use default App Engine service account
    USE_FIRESTORE_EMULATOR = False
else:
    # Development: Can use emulator or real Firestore
    USE_FIRESTORE_EMULATOR = os.environ.get("FIRESTORE_EMULATOR_HOST") is not None


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Login settings
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "apartments:index"
LOGOUT_REDIRECT_URL = "login"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO" if not DEBUG else "DEBUG",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apartments": {
            "handlers": ["console"],
            "level": "INFO" if not DEBUG else "DEBUG",
            "propagate": False,
        },
        "google.cloud.firestore": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# Google OAuth2 Settings - Fetch from Secret Manager in production, env vars in development
def get_oauth_credentials():
    """Fetch OAuth credentials from Secret Manager in production or environment variables in development."""
    if DEBUG:
        # Use environment variables in development
        return {
            "key": os.getenv("GOOGLE_OAUTH2_KEY", ""),
            "secret": os.getenv("GOOGLE_OAUTH2_SECRET", ""),
        }
    else:
        # Fetch from Google Secret Manager in production
        try:
            from google.cloud import secretmanager

            client = secretmanager.SecretManagerServiceClient()

            # Fetch OAuth key
            key_name = f"projects/comparison-tools-479102/secrets/google-oauth2-key/versions/latest"
            key_response = client.access_secret_version(request={"name": key_name})
            oauth_key = key_response.payload.data.decode("UTF-8")

            # Debug: Print OAuth key value
            print(f"DEBUG: oauth_key = '{oauth_key}'")
            print(f"DEBUG: oauth_key length = {len(oauth_key)}")

            # Fetch OAuth secret
            secret_name = f"projects/comparison-tools-479102/secrets/google-oauth2-secret/versions/latest"
            secret_response = client.access_secret_version(
                request={"name": secret_name}
            )
            oauth_secret = secret_response.payload.data.decode("UTF-8")

            # Debug: Print OAuth secret value
            print(f"DEBUG: oauth_secret = '{oauth_secret}'")
            print(f"DEBUG: oauth_secret length = {len(oauth_secret)}")

            # Validate that credentials are not empty or None
            if not oauth_key or not oauth_key.strip():
                raise ValueError("OAuth key is empty or contains only whitespace")

            if not oauth_secret or not oauth_secret.strip():
                raise ValueError("OAuth secret is empty or contains only whitespace")

            return {"key": oauth_key.strip(), "secret": oauth_secret.strip()}

        except Exception as e:
            import logging

            logger = logging.getLogger(__name__)
            logger.error(f"Failed to fetch OAuth credentials from Secret Manager: {e}")
            # Fallback to environment variables if Secret Manager fails
            return {
                "key": os.getenv("GOOGLE_OAUTH2_KEY", ""),
                "secret": os.getenv("GOOGLE_OAUTH2_SECRET", ""),
            }


# Get OAuth credentials
oauth_creds = get_oauth_credentials()
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = oauth_creds["key"]
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = oauth_creds["secret"]

# Social Authentication Settings
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Only add Google OAuth backend if credentials are available
if SOCIAL_AUTH_GOOGLE_OAUTH2_KEY and SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET:
    AUTHENTICATION_BACKENDS.insert(0, "social_core.backends.google.GoogleOAuth2")

# Security validation for OAuth credentials
if not DEBUG and (
    not SOCIAL_AUTH_GOOGLE_OAUTH2_KEY or not SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
):
    import sys
    import logging

    logger = logging.getLogger(__name__)
    logger.warning("WARNING: Google OAuth credentials not configured for production!")
    logger.warning(
        "Google Sign-In will not be available. Set GOOGLE_OAUTH2_KEY and GOOGLE_OAUTH2_SECRET environment variables"
    )
    logger.warning("App will continue to run with Django authentication only")
    # Comment out the error raising to allow app to start without OAuth
    # if "runserver" in sys.argv or "migrate" not in sys.argv:
    #     # Don't fail on migrations, but fail on server startup
    #     raise ValueError("Google OAuth credentials required for production deployment")

# Development warning for missing credentials
if DEBUG and (
    not SOCIAL_AUTH_GOOGLE_OAUTH2_KEY or not SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
):
    import logging

    logger = logging.getLogger(__name__)
    logger.warning("Google OAuth credentials not configured.")
    logger.warning("Create .env file with GOOGLE_OAUTH2_KEY and GOOGLE_OAUTH2_SECRET")
    logger.warning("See ENVIRONMENT_SECURITY.md for setup instructions")

# Social Auth URLs
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/"
SOCIAL_AUTH_LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Social Auth Pipeline (customize user creation)
SOCIAL_AUTH_PIPELINE = [
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
]

# Additional Social Auth Settings
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ["first_name", "last_name"]

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# Session Configuration
if not DEBUG:
    # On App Engine (production), use cache-based sessions to avoid SQLite database writes
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

    # Also configure messages to not use database
    MESSAGE_STORAGE = "django.contrib.messages.storage.fallback.FallbackStorage"
else:
    # In development, use default database sessions
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Session security settings
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 1 day
