# Generated by Django 6.0 on 2025-12-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentclientrelationship",
            name="invite_code",
            field=models.CharField(max_length=50),
        ),
    ]
