# Generated by Django 6.0 on 2026-01-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_remove_invite_code_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentclientrelationship',
            name='invite_code',
            field=models.ForeignKey(blank=True, help_text='The invite code used to establish this relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='homes.agentinvitecode'),
        ),
    ]
